// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('DefaultSuite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('wandavision', async function() {
    // Test name: wandavision
    // Step # | name | target | value
    // 1 | open | https://www.imdb.com/ | 
    await driver.get("https://www.imdb.com/")
    // 2 | setWindowSize | 1042x1021 | 
    await driver.manage().window().setRect(1042, 1021)
    // 3 | click | id=suggestion-search-container | 
    await driver.findElement(By.id("suggestion-search-container")).click()
    // 4 | click | id=suggestion-search | 
    await driver.findElement(By.id("suggestion-search")).click()
    // 5 | type | id=suggestion-search | wandavision
    await driver.findElement(By.id("suggestion-search")).sendKeys("wandavision")
    // 6 | sendKeys | id=suggestion-search | ${KEY_ENTER}
    await driver.findElement(By.id("suggestion-search")).sendKeys(Key.ENTER)
    // 7 | runScript | window.scrollTo(0,114) | 
    await driver.executeScript("window.scrollTo(0,114)")
    // 8 | click | linkText=WandaVision | 
    await driver.findElement(By.linkText("WandaVision")).click()
    // 9 | click | css=strong > span | 
    await driver.findElement(By.css("strong > span")).click()
    // 10 | click | css=strong > span | 
    await driver.findElement(By.css("strong > span")).click()
    // 11 | click | css=.ratingValue | 
    await driver.findElement(By.css(".ratingValue")).click()
    // 12 | click | linkText=TRIVIA | 
    await driver.findElement(By.linkText("TRIVIA")).click()
    // 13 | runScript | window.scrollTo(0,56) | 
    await driver.executeScript("window.scrollTo(0,56)")
  })
})
